### ISSUE TITLE
Error while starting a terminal of the device. But code can be pushed to the device.

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#323] opened 2017-02-03 22:49 UTC
1) Create a workspace with some sample project.
2) Connect the device.
3) Disconnect the device from network (or just turn off and on again)
4) In IDE, click on the terminal of the listed device. 
5) Error will appear "Connection failed with the terminal"
6) IDE does not allow to open the terminal at all.
7) Now, try to push any file or project to the listed device.
8) Code pushed successfully.
9) To get the terminal connection again, developer has to click on Artik icon, disconnect and connect again.
10) Also, click on "Update SDK and API". The "Manage SDK/APIs" window displays "Connection not established with the device".
![terminal-error-code pushed](https://cloud.githubusercontent.com/assets/21373498/22611487/ae3c81b0-ea1f-11e6-8748-523d5e93831d.PNG)
![terminaleroor-update sdk error-code pushed](https://cloud.githubusercontent.com/assets/21373498/22611503/c5226b06-ea1f-11e6-9977-20bb75c1a335.PNG)

**Comment by eivantsov** [comment] 2017-02-05 06:44
@v-prabhu when you power off your device, don't you see a popup saying that device is unavailable and you have been disconnected from it?

I tried but cannot reproduce this one.

When I power off my device I see the following behavior:

https://www.youtube.com/watch?v=2ACGoTXmvLY

**Comment by eivantsov** [comment] 2017-02-05 09:32
Although at times I am also able to reproduce:

![image](https://cloud.githubusercontent.com/assets/5337267/22625146/bf552f42-eb96-11e6-97bb-e1924c6778a2.png)

**Comment by eivantsov** [comment] 2017-02-06 12:26
@v-prabhu we're considering a bit different mechanism of checking if the device is online. Now it might be possible that when a device is rebooting, health check service thinks the device is online.

I cannot reliably reproduce it. Happens to me, maybe 2 times out of 20.

**Comment by v-prabhu** [comment] 2017-02-06 17:50
@eivantsov This scenario is happening to me every time. I am not getting any alert to connect if the artik is rebooting or turned off.

**Comment by eivantsov** [comment] 2017-02-06 18:00
@v-prabhu are you certain you have 1.3.2 version? I have tried it with 2 devices in different network (once scenario involved a remote device). It mostly works and occasionally an alert does not appear - we will play with ping timeout to make sure the device availability is always under control.

**Comment by v-prabhu** [comment] 2017-02-06 19:52
@eivantsov I tried again with the steps you mentioned in the video. When I try I am getting the following:
https://youtu.be/F27F7hwwDiQ

**Comment by eivantsov** [comment] 2017-02-16 18:43
Fixed in master

**Closed by eivantsov** 2017-02-16 18:43 UTC
Labels: kind/question
