### ISSUE TITLE
Restart workspace after updating SDK is failing with error

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#302] opened 2017-01-28 00:33 UTC
I am trying "Update SDK and API" feature of IDE. Once updating the SDK is successful, click on "Restart Now" button in the confirmation alert. This will result in the error. 
![capture](https://cloud.githubusercontent.com/assets/21373498/22392461/4ff8947a-e4ae-11e6-9c7f-4a46aea75242.PNG)

**Comment by eivantsov** [comment] 2017-01-28 20:54
@v-prabhu does it happen when you choose not to start from a snapshot?

**Comment by v-prabhu** [comment] 2017-02-03 22:00
@eivantsov With the IDE 1.3.2 release, the error while restarting the workspace is fixed. However the error is introduced after restarting and while recovering the workspace from snapshot.
1) Update SDK and API
2) Click "Restart" in the alert
3) After restart,  "Recovering from snapshot" alert will appear.
4) Click on "Yes"

IDE shows error alert and could not be recovered.
![recover from snapshot](https://cloud.githubusercontent.com/assets/21373498/22610175/0c88cf28-ea19-11e6-9d3b-c7f6d5e323b1.PNG)
![recover from snapshot-2](https://cloud.githubusercontent.com/assets/21373498/22610177/102f91de-ea19-11e6-803c-2815e87477d1.PNG)

**Comment by eivantsov** [comment] 2017-02-06 11:18
@v-prabhu create a new workspace. Now that snapshots are off in Artik, the old workspace configuration still uses it.Just create a new workspace.

**Comment by eivantsov** [comment] 2017-02-10 05:33
Closing the issue. Fixed in 1.3.2

**Comment by v-prabhu** [comment] 2017-02-24 00:47
@eivantsov The issue now introduced in IDE 1.4.0. Restarting workspace after "Update SDK and APIs" is failing with error.
![capture](https://cloud.githubusercontent.com/assets/21373498/23285707/bba8daf6-f9e7-11e6-9eeb-ffef2ed277ce.PNG)

**Comment by eivantsov** [comment] 2017-02-24 08:15
@v-prabhu I cannot reproduce, probably a caching issue. Try it in an incognito mode.

**Comment by v-prabhu** [comment] 2017-03-01 00:58
@eivantsov I tried this scenario in the incognito mode and also in the Mac installer. Please check the video:
https://youtu.be/nex81t5QfDY

**Comment by eivantsov** [comment] 2017-03-01 07:42
Confirmed on Windows.

**Closed** 2017-03-07 10:07 UTC
Labels: kind/bug, priority/P1, sprint/next-sprint, team/ide
