### ISSUE TITLE
Delete the workspace and create a new with the same name and same sample project as deleted one 

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#324] opened 2017-02-03 22:53 UTC
1) Create a workspace "Test-Workspace" by selecting any sample projects "artik-samples".
2) After workspace is up and running, delete the workspace.
3) Again create a new workspace with the same name "Test-Workspace" with the same sample project "artik-samples".
4) Error alert will be displayed after the workspace is up and sample project is being loaded.
![error creating project -](https://cloud.githubusercontent.com/assets/21373498/22611649/92a4d424-ea20-11e6-87c6-0fc3982aac20.PNG)

**Comment by eivantsov** [comment] 2017-02-05 06:30
@v-prabhu I will try to reproduce and qualify it as bug.

**Comment by v-prabhu** [comment] 2017-02-06 20:08
@eivantsov Please see the video below:
 https://youtu.be/mHFqJiR_Y_c

**Comment by eivantsov** [comment] 2017-02-07 11:03
Yes, confirmed. Thank you.

**Comment by svor** [comment] 2017-02-17 15:32
The same problem was in CHE, now it's fixed (https://github.com/eclipse/che/pull/4122/files)

**Comment by eivantsov** [comment] 2017-02-20 06:45
Fixed. @v-prabhu you may check it with the latest nightly image

**Comment by v-prabhu** [comment] 2017-02-21 18:25
The issue still persists with nightly image. Any solution for this issue.

**Comment by eivantsov** [comment] 2017-02-21 18:27
Did you clean local storage mounted into :/data?

**Comment by v-prabhu** [comment] 2017-02-21 19:05
Yes. I tried installing from scratch. Deleted all the images and also deleted all the local storage.

**Comment by eivantsov** [comment] 2017-02-22 03:23
Cannot reproduce. Must be a cache issue ir smth. We will release today.

**Comment by v-prabhu** [comment] 2017-02-22 22:12
This issue still persists with v.1.4.0. 
However, if we create the workspace without any sample projects, then this issue is not observed. 

Follow the scenario below to reproduce the issue:
1) Create a workspace "Test-Workspace" with sample project "artik-samples".
2) After workspace is up and running delete the workspace.
3) Observe the "workspaces" folder in :/data. The folder "Test-Workspace" still exists.
4) Now, try to create a new workspace with the same name "Test-Workspace" with the same sample project "artik-samples". The error alert displayed while creating the project.

**Comment by eivantsov** [comment] 2017-02-23 10:07
Reopened. Win 7 and 8 need a patch

**Comment by v-prabhu** [comment] 2017-03-07 22:33
Windows-10 Screen capture:
https://youtu.be/mjCrN4xWpgY

**Comment by eivantsov** [comment] 2017-03-16 15:08
Fixed in 1.5.0

**Closed by eivantsov** 2017-03-16 15:08 UTC
Labels: kind/bug, priority/P1, sprint/current-sprint, team/ide
