### ISSUE TITLE
Deleting the workspace in IDE is not deleting the workspace from local PC (where docker installed) directory

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#318] opened 2017-02-03 22:05 UTC
If the workspace is deleted from IDE, the same should be deleted from the server PC also. Because, as developer, if I want to create new workspace with the same name, the previously deleted workspace and the projects will be loaded.

**Comment by eivantsov** [comment] 2017-02-07 11:47
Duplicate of https://github.com/eclipse/che/issues/3973

**Comment by vinokurig** [comment] 2017-02-15 14:47
Fixed in https://github.com/eclipse/che/issues/3973

**Comment by v-prabhu** [comment] 2017-02-22 22:09
This issue still persists with v.1.4.0. 
However, if we create the workspace without any sample projects, then deleting the workspace deletes from :/data folder as well.

Follow the scenario below to reproduce the issue:
1) Create a workspace "Test-Workspace" with sample project "artik-samples".
2) After workspace is up and running delete the workspace.
3) Observe the "workspaces" folder in :/data. The folder "Test-Workspace" still exists.

**Comment by eivantsov** [comment] 2017-03-04 05:00
Related - https://github.com/codenvy/artik/issues/324

**Comment by v-prabhu** [comment] 2017-03-07 22:33
Windows-10 screen capture:
https://youtu.be/mjCrN4xWpgY

**Comment by eivantsov** [comment] 2017-03-15 09:33
Fixed in Che

**Closed by eivantsov** 2017-03-15 09:33 UTC
Labels: kind/bug, status/code-review

**Comment by v-prabhu** [comment] 2017-03-15 17:04
@eivantsov Can you please help me to know whether I can verify this fix with the nightly build or should I wait for the next release?

**Comment by eivantsov** [comment] 2017-03-15 17:12
I will let you know when a new release is available.
