### ISSUE TITLE
Windows and Mac installer :  Deleting a project file or compiled binary in the IDE workspace is not deleting the same from the connected artik device

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#376] opened 2017-03-04 00:31 UTC
1) Create a workspace with some sample projects.
2) Connect a artik device.
3) The project folder gets copied in the artik device.
4) Delete any file in the loaded project from IDE.
5) The file is not synced with the device.

Note: This issue is with Windows-10 and Mac installer only.

**Comment by eivantsov** [comment] 2017-03-04 06:08
Cannot reproduce with Win 10. Every time I delete a file, it gets deleted on my Artik board in 1-2 seconds.

**Comment by v-prabhu** [comment] 2017-03-08 00:50
I am not able to find the exact scenario for this issue. But, Yes, if I try above mentioned steps multiple times, with the same sample projects added during workspace creation, I encounter this issue. Also, the deleted is deleted from artik device and after some time again appears. Not sure of the scenario though. I assume this issue is related with https://github.com/codenvy/artik/issues/318.

**Comment by eivantsov** [comment] 2017-03-08 04:24
I need steps to reproduce. I tried but failed to reproduce myself.

**Comment by eivantsov** [comment] 2017-03-23 13:28
Closed as cannot reproduce.

**Closed by eivantsov** 2017-03-23 13:28 UTC
Labels: kind/question
