### ISSUE TITLE
No error alert if the IDE lost connection with the Docker (Server)

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#335] opened 2017-02-09 23:05 UTC
No error alert is being shown if the IDE looses connection with the docker. Meaning, if the network resets or network disconnected, IDE losses connection with the docker. The user should be alerted of this disconnection and should not be allowed to attempt any operations.
1) Start the docker.
2) Launch IDE in browser.
3) Create a workspace.
4) Wait till the workspace is up and running.
5) Disconnect the network (wi-fi).
6) IDE does not show the alert for disconnection. However, when the user clicks on "Manage Artik Devices" overlapping "Loading" and "Discovering devices" alerts display.

![disconnected from docker](https://cloud.githubusercontent.com/assets/21373498/22806903/3580f56c-eed9-11e6-9824-c52f9ef22385.PNG)

**Comment by eivantsov** [comment] 2017-02-10 05:27
Cannot reproduce. Disconnecting from network or turning off wifi did not impact IDE.

**Comment by eivantsov** [comment] 2017-02-20 07:00
@v-prabhu you are on Win 7, right?

**Comment by v-prabhu** [comment] 2017-02-21 23:52
Yes.

**Comment by eivantsov** [comment] 2017-02-22 03:25
Cannot reproduce on Win 8 and 10.

Do you just disconnect from network or turn off networking at all?

**Comment by v-prabhu** [comment] 2017-02-22 18:22
I usually start IDE on a open network. But when the IDE is open and I change to secured network, this issue is observed.

**Comment by eivantsov** [comment] 2017-02-22 19:35
I think I need more details to be able to reproduce it. On win 8, I just disconnect from a network, and the IDE is working fine.

**Comment by eivantsov** [comment] 2017-03-29 11:16
Fixed by https://github.com/eclipse/che/issues/4311

**Closed by eivantsov** 2017-03-29 11:16 UTC
Labels: kind/question
