### ISSUE TITLE
Github OAuth problem: redirecturi "connect time out" and Cannot create artik sample project

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik#122] opened 2016-08-23 06:12 UTC
**Description of problem:**
1. At the Github OAuth process, always "connect time out" at uri redirection step. 
2. The artik sample project cannot be created.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Firefox

**Steps to Reproduce:**
1. First time to create artik sample project failed for the reason "cannot open git-upload-pack" in IDE, console message is "unsupported oauth provider github"
   ![2_create sample project fail](https://cloud.githubusercontent.com/assets/20897963/17881755/7d8d7a94-693a-11e6-8e18-04025653be61.png)
2. Register OAuth applications in Github
   ![3_register application authorize](https://cloud.githubusercontent.com/assets/20897963/17881766/86d9e498-693a-11e6-9edd-15a237e4d767.png)
3. Set the "conf/che.properties"
   ![5_modify che-properties](https://cloud.githubusercontent.com/assets/20897963/17881772/8c2dcb30-693a-11e6-8554-1595b99f4214.png)
4. Restart the artik-ide, "Profile->Preferences->SSH->VCS", click the cat icon and aggree the authorization.
   ![6_git oauth cat](https://cloud.githubusercontent.com/assets/20897963/17881800/bb7defe6-693a-11e6-9b0e-d4868e3dd7d8.png)
   ![7_confirm authorize](https://cloud.githubusercontent.com/assets/20897963/17881799/badebff2-693a-11e6-8ed1-93f13be3f4dd.png)
5. Always get "connect time out" message at the final step. The Github key cannot be uploaded.
   ![10_connect time out](https://cloud.githubusercontent.com/assets/20897963/17881812/da81744e-693a-11e6-9abf-e4699f19a341.png)
   ![11_fail to authorize application on github](https://cloud.githubusercontent.com/assets/20897963/17881813/daa7baa0-693a-11e6-9756-9a22bbf4ce43.png)
   
   But，Github site shows the authorization success.
   ![12_](https://cloud.githubusercontent.com/assets/20897963/17881911/85856e86-693b-11e6-98d7-41cbe034829a.png)
6. Second time to create artik sample project failed without prompting "unsupported oauth provider github" at console.
   ![14_create sample project fail_2](https://cloud.githubusercontent.com/assets/20897963/17881916/9006758a-693b-11e6-86df-f0f1700acf10.png)

**Actual Results:**
Github OAuth authorization failed. Artik sample project cannot be created.

**Expected Results:**
Github OAuth authorized successful. Artik sample project can be created.

**Comment by laralijuan** [comment] 2016-08-23 06:17
I have referred:
https://eclipse-che.readme.io/docs/git#section-github
https://eclipse-che.readme.io/docs/configuration#github-oauth
https://github.com/eclipse/che/issues/1694

And, tried using my testing pc's ip to instead the "localhost", unfortunately, all failed.

**Comment by eivantsov** [comment] 2016-08-23 07:43
@laralijuan are you  using a different network? You were able to create sample projects before, right?

Can you just start a workspace and try to git clone smth in the terminal?

**Comment by eivantsov** [comment] 2016-08-23 07:48
@laralijuan as to setting up oAuth you did everything OK. It's is most certainly a network related issue.

**Comment by laralijuan** [comment] 2016-08-23 08:01
hi, @eivantsov I have never create artik sample project before.  Only other type project creation is OK.
Does creating artik sample project must set the Github OAuth?

I do "git clone https://github.com/che-samples/artik-blink-led.git" successful in my testing PC( run IDE Server).
but failed on the artik device. (prompting: "Could not resolve host: github.com")
and also failed on workspace's default machine. ("Failed to connect to github.com port 443: Connection timed out")

Could you give me some suggestions? Many thanks.

**Comment by eivantsov** [comment] 2016-09-02 07:00
Can you git clone in the terminal of the workspace machine? It looks like there are networking issues in the docker container.

is this still reproducible?

**Comment by laralijuan** [comment] 2016-09-04 14:37
@eivantsov yes, I can git clone successful in workspace's default machine.

I have set proxy for testing PC and workspace (in che.properites), both of them can git clone success. but still creating artik sample project failed.

**Comment by bmicklea** [comment] 2016-11-24 16:06
@laralijuan is this still a problem?

**Comment by eivantsov** [comment] 2017-02-20 07:10
Now Artik CLI can inherit proxy settings from Docker daemon. Closing the issue. Feel free to reopen if the problem persists.

**Closed by eivantsov** 2017-02-20 07:10 UTC
Labels: kind/question
