### ISSUE TITLE
Can not create the workspace in windows-8

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#372] opened 2017-03-03 00:27 UTC
There is no particular scenario for this. However, if it fails once then can not create the workspace again anytime after.

![not able to create workspace](https://cloud.githubusercontent.com/assets/21373498/23533206/0e8e00fc-ff65-11e6-83ae-39109a0cab37.PNG)

**Comment by eivantsov** [comment] 2017-03-03 06:36
It does look like Docker connectivity issue.  Can you run `docker pull alpine` in your cmd and check if it is a success?

**Comment by eivantsov** [comment] 2017-03-15 12:03
Closing as cannot reproduce.

**Closed by eivantsov** 2017-03-15 12:03 UTC
Labels: kind/question
